### ISSUE TITLE
Improving search

### ISSUE THREAD

**Issue by pfranck** [docuowl/docuowl#11]
I think you can use https://lunrjs.com/docs/index.html to improve search. Let me know if you need help integrating it.

**Comment by ofeefo** [comment]
Hi @pfranck ! Thank you for the suggestion and sorry for our delay. 
We already discussed a bit about search engines on #5, where we decided to keep our current search.

"*The search we are providing here would be just to aid people searching for contents (since it will by default avoid indexing code blocks). For all other needs and purposes, the browser native search would be enough for all use cases, specially since Docuowl emits a single HTML file.*"

If you have any other suggestions, feel free to open another issue. :)
