### ISSUE TITLE
Release for Windows?

### ISSUE THREAD

**Issue by jcs090218** [docuowl/docuowl#22]
Hi, I am on Windows 10! Is there a plan for Windows release?

Thanks!

**Comment by heyvito** [comment]
Hey there!
Not sure about that. @ofeefo care checking whether we can run on Windows?

**Comment by ofeefo** [comment]
Hi @jcs090218! Sorry for the delay. We've been quite busy these days :/

There's a lot of things in windows that can be a pain for users to deal with in order to run/compile the tool, such as adding things to path manually like `TDM-GCC-64` or the tool itself, and we also don't want to force anyone to run `.reg / .exe` files or anything like that, so we're not looking to make it viable for windows. Maybe you can try to run it on WSL, but I haven't tested it at all.

Sorry for that, but that's it for now. If you have any other questions, let us know =)
