### ISSUE TITLE
Suggestion for full-text search (stork)

### ISSUE THREAD

**Issue by netstx** [docuowl/docuowl#5]
I just recently discovered [stork](https://github.com/jameslittle230/stork), and I think it could be a good "3rd party" (self-hosted, not cloud!) solution for full-text search without having to reinvent the wheel inside Docuowl. 

As far as I know, stork currently doesn't recursively add files from a directory to its database, but once your Docuowl tree is well established, you could configure stork (or write a script to autogen the config if you have tons of files) and it should work well (although I haven't tested it with Docuowl yet...).

On the Docuowl side, perhaps there could be an integration with stork so that the search bar uses either the built-in search feature or stork's search. 

Just a thought!

**Comment by heyvito** [comment]
Hey @netstx! Thank you for the suggestion!
The initial idea was to emit a single HTML file, but since we started using WASM for FTS, indeed `stork` is indeed a great option!
I'll take a look at this ASAP!

Once again, thank you for the suggestion! ♥️

**Comment by netstx** [comment]
@heyvito Glad you found it useful! I am not fluent in Go, but I'd be happy to help test this feature in the future, just mention me here and I will help where I can :)

**Comment by heyvito** [comment]
Hi there @netstx!

I discussed with other members, and we sadly determined it would be not ideal to use Stork as a dependency of Docuowl.
In order to use it, we would need to either:

a) Distribute a Stork binary together with Docuowl, which would end up with more than a single binary; or
b) Compile Stork as a `cdylib` and use it through a FFI. To do that, we would need to compile Stork to all platforms we are currently supporting (Darwin ARM64/x86_64, Linux ARM64/x86_64), and that would require us to maintain a build pipeline for all those platforms. Also, FFI between Rust and Go is a slippery slope, and that would require extra work in order to maintain that integration.

The search we are providing here would be just to aid people searching for contents (since it will by default avoid indexing code blocks). For all other needs and purposes, the browser native search would be enough for all use cases, specially since Docuowl emits a single HTML file. ✨ 

It is really sad we can't use it. Stork is an _awesome_ project, and I really wanted to be able to use it here. :(

I hope this explains our reasoning, and please let me know in case I can provide you further information!

**Comment by netstx** [comment]
@heyvito that makes a lot of sense, nevertheless thanks for putting this much thought into my suggestion!
